### ISSUE TITLE
Can't find the source-dir directory

### ISSUE THREAD

**Issue by koobai** [ryand56/r2-upload-action#256]
I defined a source-dir directory, e.g. koobaiblog, but after running Actions I get ENOENT: no such file or directory, scandir 'koobaiblog'.
I'm sure there is a folder "xxx" in the repository root folder.

<img width="1051" alt="image" src="https://github.com/ryand56/r2-upload-action/assets/50470569/f2ceb829-2de5-4c26-acb1-f12ce747d688">

**Comment by ryand56** [comment]
Hi there, please send me your workflow file. Thanks

**Comment by koobai** [comment]
Hi, This is my workflow. Thank you
```
name: Sync R2

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'koobaiblog/**'  # 监视koobaiblog目录及其子目录下的文件变化

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: ryand56/r2-upload-action@v1.2
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: koobaiblog
```
