### ISSUE TITLE
source-dir does not support some environment variables

### ISSUE THREAD

**Issue by CAB233** [ryand56/r2-upload-action#431]
Based on this [issue](https://github.com/actions/runner/issues/2058), we know that `$GITHUB_WORKSPACE` is equivalent to `/__w/<repo_name>/<repo_name>`，however, when using the environment variable `$GITHUB_WORKSPACE`, an error occurs, while using its corresponding file path is fine.
```
- name: upload
  id: upload-r2
  continue-on-error: true
  uses: ryand56/r2-upload-action@latest
  with:
    r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
    r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
    r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
    r2-bucket: ${{ secrets.R2_BUCKET }}
    source-dir: $GITHUB_WORKSPACE
    destination-dir: archlinux

- name: upload if failure
  if: steps.upload-r2.outcome == 'failure'
  uses: ryand56/r2-upload-action@latest
  with:
    r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
    r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
    r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
    r2-bucket: ${{ secrets.R2_BUCKET }}
    source-dir: /__w/myAUR/myAUR
    destination-dir: archlinux/x86_64
```
Here are the corresponding results in action, only the second assignment will succeed
```
Run ryand56/r2-upload-action@latest
  with:
    r2-account-id: ***
    r2-access-key-id: ***
    r2-secret-access-key: ***
    r2-bucket: ***
    source-dir: $GITHUB_WORKSPACE
    destination-dir: archlinux
    output-***-url: true
/usr/bin/docker exec  f09f6950beda6b27093c68d4712d555c9a59c811f3babdc79b49e260b1805436 sh -c "cat /etc/*release | grep ^ID"
Error Error: ENOENT: no such *** or directory, scandir '$GITHUB_WORKSPACE'
    at Object.readdirSync (node:fs:1507:26)
    at getFileList (***:///__w/_actions/ryand56/r2-upload-action/latest/webpack:/r2-upload-action/src/index.ts:36:1)
    at run (***:///__w/_actions/ryand56/r2-upload-action/latest/webpack:/r2-upload-action/src/index.ts:57:1)
    at ***:///__w/_actions/ryand56/r2-upload-action/latest/webpack:/r2-upload-action/src/index.ts:114:1
    at ***:///__w/_actions/ryand56/r2-upload-action/latest/dist/index.js:39889:3
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '$GITHUB_WORKSPACE'
}
Error: ENOENT: no such *** or directory, scandir '$GITHUB_WORKSPACE'
```
```
Run ryand56/r2-upload-action@latest
  with:
    r2-account-id: ***
    r2-access-key-id: ***
    r2-secret-access-key: ***
    r2-bucket: ***
    source-dir: /__w/myAUR/myAUR
    destination-dir: archlinux/x86_64
    output-***-url: true
/usr/bin/docker exec  f09f6950beda6b27093c68d4712d555c9a59c811f3babdc79b49e260b1805436 sh -c "cat /etc/*release | grep ^ID"
/__w/myAUR/myAUR/howdy-beta-git-2.6.1.r245.gaa75c76-1-x86_64.pkg.tar.zst
/__w/myAUR/myAUR
archlinux/x86_64
archlinux/x86_64/howdy-beta-git-2.6.1.r245.gaa75c76-1-x86_64.pkg.tar.zst
R2 Success - /__w/myAUR/myAUR/howdy-beta-git-2.6.1.r245.gaa75c76-1-x86_64.pkg.tar.zst
...
```
