### ISSUE TITLE
Directory structure is ignored from v1.3

### ISSUE THREAD

**Issue by yoshiomiyamae** [ryand56/r2-upload-action#440]
I have been using r2-upload-action from v1.2.3. Today it was updated to v1.3, and after that, the directory structure is ignored.
My setting is:
```yaml
      - name: Upload to R2 (public)
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{  secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET_NAME }}
          source-dir: /tmp/app/frontend/public/
          destination-dir: ./
```

And for instance, there is a file:
```
/tmp/app/frontend/.next/static//chunks/1521-8b86bc31a7492024.js
```
and it was uploaded to:
```
_next/static/1770-f3a38e969cea9a80.js
```

The part of the log is this:
```
R2 Info - Uploading /tmp/app/frontend/.next/static//chunks/1521-8b86bc31a7492024.js (16.03 KB) to _next/static/1521-8b86bc31a7492024.js
using put object upload for _next/static/1521-8b86bc31a7492024.js
R2 Success - /tmp/app/frontend/.next/static//chunks/1521-8b86bc31a7492024.js
/tmp/app/frontend/.next/static//chunks/1734-20519dd5a1c[60](https://github.com/yukonsky/toyshare/actions/runs/10172917286/job/28136340977#step:5:61)56e.js
/tmp/app/frontend/.next/static/
./_next/static
_next/static/1734-20519dd5a1c6056e.js
```
