### ISSUE TITLE
Need a short path url

### ISSUE THREAD

**Issue by Yecgaa1** [ryand56/r2-upload-action#458]
Thank you first for your action repository
I found that when I need to upload a file located in a deeper path, its uploaded path is very long and the filename contains the file path, which is not conducive to my subsequent file automation operations. Is there something wrong with the way I'm using it or is it something that needs to be improved. My action is running on windows, is this relevant?

```yml
name: Windows-Qt6.5.1-BuildUpdate-I2CTool
on:
  push:
    paths:
      - 'api/**'
      - 'components/IICDeviceBasic/**'
      - 'thirdLib/**'
      - 'thirdTarget_I2CTool/**'
      - '.github/workflows/**'
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
        include:
          - qt_ver: 6.5.3
            qt_arch: win64_msvc2019_64
            msvc_arch: x64
            qt_arch_install: msvc2019_64
    env:
      targetName: I2CTool.exe
      fileName: I2CTool
    steps:
      #准备仓库
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 50
          fetch-tags: true

     
      #上传I2CTool安装包
      - uses: ryand56/r2-upload-action@latest # Can be any release
        id: cloudflare_r2_I2CTool
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: xtxtools
          source-dir: ./build/xtxTools-updatePackage-I2CTool.zip
          destination-dir: ./ # Can be anything as long as it is an actual path
          output-file-url: 'true' # defaults to true
          multipart-size: 100 # If the file size is greater than the value provided here, then use multipart upload
          max-retries: 5 # The maximum number of retries it takes to upload a multipart chunk until it moves on to the next part
          multipart-concurrent: true # Whether to concurrently upload a multipart chunk
          keep-file-fresh: 'true' # defaults to false

```

output is 
```json
{"value":"{\"D:\\\\a\\\\WirelessMonitor\\\\WirelessMonitor\\\\build\\\\xtxTools-updatePackage-I2CTool.zip\":\"https://xtxtools.***.r2.cloudflarestorage.com/D%3A%5Ca%5CWirelessMonitor%5CWirelessMonitor%5Cbuild%5CxtxTools-updatePackage-I2CTool.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=9bfe57cc3ddaac5ddbb9f3211445845a%2F20240825%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20240825T165514Z&X-Amz-Expires=900&X-Amz-Signature=195f7212ceb008a0620123313c69f5a06f65370e9161f1582126b3869621db&X-Amz-SignedHeaders=content-length%3Bhost%3Bif-none-match&x-id=PutObject\"}"}
```
