### ISSUE TITLE
Feature: Provide multiple files to upload

### ISSUE THREAD

**Issue by Edouard127** [ryand56/r2-upload-action#472]
I am using this action in order to upload artifacts to my R2 Bucket and I've come into the following issue:

You cannot upload multiple files from different folders in one go like this
```yaml
      - name: Upload Files
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY }}
          r2-secret-access-key: ${{ secrets.R2_ACCESS_SECRET }}
          r2-bucket: ${{ secrets.R2_BUCKET_NAME }}
          source-dir: |
              './file1.jar'
              './file2.jar'
              './file3.jar'
          destination-dir: ${{ env.DATE }}-${{ env.COMMIT_HASH }}
```

In this case, the directory provided to https://github.com/ryand56/r2-upload-action/blob/master/src/utils.ts#L20 is as follow:
"./file1.jar\n" + "./file2.jar\n" + "./file3.jar"

Implementation of such feature is fairly simple, check if the string contains \n, if so, recursively run the function for each split path
