### ISSUE TITLE
Uploading a single file to root directory

### ISSUE THREAD

**Issue by Him188** [ryand56/r2-upload-action#484]
```yaml
      - uses: ryand56/r2-upload-action@v1.3.2
        with:
          r2-secret-access-key: ${{ secrets.R2_ACCESS_SECRET_KEY }}
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-bucket: sub
          source-dir: ./subs/
          destination-dir: ./
```

I have a `subs/css1.json` locally. I want to upload it to the root directory of the bucket. However using the above configuration the file path in R2 is `subs/sub1.json`. 
![image](https://github.com/user-attachments/assets/2c12129e-c257-48bf-92b7-90ca0db6eb96)

With `source-dir: ./subs/css1.json`, the action even generated more incorrect path:
![image](https://github.com/user-attachments/assets/c4dc2d5f-4095-4f01-8790-cda344100884)

It seems it's currently impossible to either upload a single file or into the root directory.
