### ISSUE TITLE
Upload all files from a directory

### ISSUE THREAD

**Issue by CodeWithShreyans** [ryand56/r2-upload-action#507]
How can I upload all files from the source directory `folder1` for example to the root of the bucket?

**Comment by ryand56** [comment]
To upload to the root of the bucket from the source directory `folder1`:
```yaml
- uses: ryand56/r2-upload-action@latest
  with:
    r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
    r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
    r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
    r2-bucket: ${{ secrets.R2_BUCKET }}
    source-dir: folder1
    destination-dir: ./
```
